from django.db import models

# Create your models here.


class userInput(models.Model):
    username = models.CharField(max_length=50, default="NULL User")
    # trading_code = models.CharField(max_length=200)
    
    select_tradingCode = [
        ("AAMRANET" , "aamra networks limited"),
        ("AAMRATECH" , "aamra technologies limited"),
        ("ABB1STMF" , "AB Bank 1st Mutual fund"),
        ("ABBANK" , "AB Bank Limited"),
        ("ACFL" , "Aman Cotton Fibrous Limited"),
        ("ACI" , "ACI Limited"),
        ("ACIFORMULA" , "ACI Formulations Limited"),
        ("ACMELAB" , "The ACME Laboratories Limited"),
        ("ACMEPL" , "ACME Pesticides Limited"),
        ("ACTIVEFINE" , "Active Fine Chemicals Limited"),
        ("ADNTEL" , "ADN Telecom Limited"),
        ("ADVENT" , "Advent Pharma Limited"),
        ("AFCAGRO" , "AFC Agro Biotech Ltd."),
        ("AFTABAUTO" , "Aftab Automobiles Limited"),
        ("AGNISYSL" , "Agni Systems Ltd."),
        ("AGRANINS" , "Agrani Insurance Co. Ltd."),
        ("AIBL1STIMF" , "AIBL 1st Islamic Mutual Fund"),
        ("AIBLPBOND" , "AIBL Mudaraba Perpetual Bond"),
        ("AIL" , "Alif Industries Limited"),
        ("AL-HAJTEX" , "Al-Haj Textile Mills Limited"),
        ("ALARABANK" , "Al-Arafah Islami Bank Ltd"),
        ("ALIF" , "Alif Manufacturing Company Ltd."),
        ("ALLTEX" , "Alltex Industries Ltd."),
        ("AMANFEED" , "Aman Feed Limited"),
        ("AMBEEPHA" , "Ambee Pharmaceuticals Ltd."),
        ("AMCL(PRAN)," , "Agricultural Marketing Company Ltd.(Pran)"),
        ("ANLIMAYARN" , "Anlimayarn Dyeing Ltd."),
        ("ANWARGALV" , "Anwar Galvanizing Ltd."),
        ("AOL" , "Associated Oxygen Limited"),
        ("APEXFOODS" , "Apex Foods Limited"),
        ("APEXFOOT" , "Apex Footwear Limited."),
        ("APEXSPINN" , "Apex Spinning & Knitting Mills Limited"),
        ("APEXTANRY" , "Apex Tannery Limited"),
        ("APOLOISPAT" , "Appollo Ispat Complex Limited"),
        #("APSCLBOND" , "APSCL Non-Convertible and Fully Redeemable Coupon Bearing Bond"),
        ("ARAMIT" , "Aramit Limited"),
        ("ARAMITCEM" , "Aramit Cement Limited"),
        ("ARGONDENIM" , "Argon Denims Limited"),
        ("ASIAINS" , "Asia Insurance Limited"),
        ("ASIAPACINS" , "Asia Pacific General Insurance Co. Ltd."),
        ("ATCSLGF" , "Asian Tiger Sandhani Life Growth Fund"),

        ("BANGAS" , "Bangas Ltd."),
        ("BANKASIA" , "Bank Asia Ltd."),
        ("BARKAPOWER" , "Baraka Power Limited"),
        ("BATASHOE" , "Bata Shoe Company Limited Bangladesh"),
        ("BATBC" , "British American Tobacco bangladesh Company Limited"),
        ("BAYLEASING" , "Bay Leasing & Investment Limited"),
        ("BBS" , "Bangladesh Building Systems Ltd."),
        ("BBSCABLES" , "BBS Cables Limited"),
        ("BDAUTOCA" , "Bangladesh Autocars Ltd."),
        ("BDCOM" , "BDCOM Online Ltd."),
        ("BDFINANCE" , "Bangladesh Finance Limited"),
        ("BDLAMPS" , "Bangladesh Lamps Limited"),
        ("BDSERVICE" , "Bangladesh Services Ltd."),
        ("BDTHAI" , "Bd.Thai Aluminium Ltd."),
        ("BDTHAIFOOD" , "BD Thai Food & Beverage Limited"),
        ("BDWELDING" , "Bangladesh Welding Electrodes Ltd."),
        ("BEACHHATCH" , "Beach Hatchery Ltd."),
        ("BEACONPHAR" , "Beacon Pharmaceuticals Limited"),
        ("BENGALWTL" , "Bengal Windsor Thermoplastics Ltd."),
        ("BERGERPBL" , "Berger Paints Bangladesh Ltd."),
        ("BEXGSUKUK" , "Beximco Green Sukuk Al Istisna'a"),
        ("BEXIMCO" , "Bangladesh Export Import Company Ltd."),
        ("BGIC" , "Bangladesh General Insurance Company Ltd."),
        ("BIFC" , "Bangladesh Industrial Fin. Co. Ltd."),
        ("BNICL" , "Bangladesh National Insurance Company Limited"),
        ("BPML" , "Bashundhara Paper Mills Limited"),
        ("BPPL" , "Baraka Patenga Power Limited"),
        ("BRACBANK" , "BRAC Bank Ltd."),
        ("BSC" , "Bangladesh Shipping Corporation"),
        ("BSCCL" , "Bangladesh Submarine Cable Company Limited"),

        ("BSRMSTEEL" , "BSRM Steels Limited"),
        ("BXPHARMA" , "Beximco Pharmaceuticals Ltd."),
        ("BXSYNTH" , "Beximco Synthetics Ltd."),
    
        ("CAPMBDBLMF" , "CAPM BDBL Mutual Fund 01"),
        ("CAPMIBBLMF" , "CAPM IBBL Islamic Mutual Fund"),
        ("CENTRALINS" , "Central Insurance Company Ltd."),
        ("CENTRALPHL" , "Central Pharmaceuticals Limited"),
        ("CITYBANK" , "The City Bank Ltd."),
        ("CITYGENINS" , "City General Insurance Co. Ltd."),
        ("CNATEX" , "C & A Textiles Limited"),
        ("CONFIDCEM" , "Confidence Cement Ltd."),
        ("CONTININS" , "Continental Insurance Ltd."),
        ("COPPERTECH" , "Coppertech Industries Limited"),
        ("CROWNCEMNT" , "Crown Cement PLC."),
        ("CRYSTALINS" , "Crystal Insurance Company Limited"),
        ("CVOPRL" , "CVO Petrochemical Refinery Limited"),
  
        ("DACCADYE" , "The Dacca Dyeing & Manufacturing Co.Ltd."),
        ("DAFODILCOM" , "Daffodil Computers Ltd."),
        ("DBH" , "Delta Brac Housing Finance Corp. Ltd."),
        ("DBH1STMF" , "DBH First Mutual Fund"),
        ("DEBARACEM" , "Aramit Cement Ltd.(Deb-14%)"),
        ("DEBBDLUGG" , "Bangladesh Luggage Ind. Ltd.(Deb-14%)"),
        ("DEBBDWELD" , "BD Welding Electrodes Ltd.(Deb-14%)"),
        ("DEBBDZIPP" , "Bangladesh Zipper Ind. Ltd.(Deb-14%)"),
        ("DEBBXDENIM" , "Beximco Denims Ltd.(Deb-14%)"),
        ("DEBBXFISH" , "Beximco Fisheries Ltd.(Deb-14%)"),
        ("DEBBXKNI" , "Beximco Knitting Ltd.(Deb-14%)"),
        ("DEBBXTEX" , "Beximco Textiles Ltd.(Deb-14%)"),
        ("DELTALIFE" , "Delta Life Insurance Company Ltd."),
        ("DELTASPINN" , "Delta Spinners Ltd."),
        ("DESCO" , "Dhaka Electric Supply Company Ltd."),
        ("DESHBANDHU" , "Deshbandhu Polymer Limited"),
        ("DGIC" , "Desh General Insurance Company Limited"),
        ("DHAKABANK" , "Dhaka Bank Ltd."),
        ("DHAKAINS" , "Dhaka Insurance Limited"),
        ("DOMINAGE" , "Dominage Steel Building Systems Limited"),
        ("DOREENPWR" , "Doreen Power Generations and Systems Limited"),
        ("DSHGARME" , "Desh Garments Ltd."),
        ("DSSL" , "Dragon Sweater and Spinning Limited"),
        ("DULAMIACOT" , "Dulamia Cotton Spinning Mills Ltd."),
        ("DUTCHBANGL" , "Dutch Bangla Bank Ltd."),
        
        ("EASTERNINS" , "Eastern Insurance Company Ltd."),
        ("EASTLAND" , "Eastland Insurance Company Ltd."),
        ("EASTRNLUB" , "Eastern Lubricants Blenders Limited"),
        ("EBL" , "Eastern Bank Ltd."),
        ("EBL1STMF" , "EBL First Mutual Fund"),
        ("EBLNRBMF" , "EBL NRB Mutual Fund"),
        ("ECABLES" , "Eastern Cables Ltd."),
        ("EGEN" , "eGeneration Limited"),
        ("EHL" , "Eastern Housing Limited"),
        ("EIL" , "Express Insurance Limited"),
        ("EMERALDOIL" , "Emerald Oil Industries Ltd."),
        ("ENVOYTEX" , "Envoy Textiles Limited"),
        ("EPGL" , "Energypac Power Generation Limited"),
        ("ESQUIRENIT" , "Esquire Knit Composite Limited"),
        ("ETL" , "Evince Textiles Limited"),
        ("EXIM1STMF" , "EXIM Bank 1st Mutual Fund"),
        ("EXIMBANK" , "Export Import(EXIM) Bank of Bangladesh Limited"),
        ("EXCH", "EXCH"),
    
        ("FAMILYTEX" , "Familytex(BD) Limited"),
        ("FARCHEM" , "Far Chemical Industries Limited"),
        ("FAREASTFIN" , "Fareast Finance & Investment Limited"),
        ("FAREASTLIF" , "Fareast Islami Life Insurance Co. Ltd."),
        ("FASFIN" , "FAS Finance & Investment Limited"),
        ("FBFIF" , "First Bangladesh Fixed Income Fund"),
        ("FEDERALINS" , "Federal Insurance Company Ltd."),
        ("FEKDIL" , "Far East Knitting & Dyeing Industries Limited"),
        ("FINEFOODS" , "Fine Foods Limited"),
        ("FIRSTFIN" , "First Finance Limited"),
        ("FIRSTSBANK" , "First Security Islami Bank Limited"),
        ("FORTUNE" , "Fortune Shoes Limited"),
        ("FUWANGFOOD" , "Fu Wang Food Ltd."),

        ("GBBPOWER" , "GBB Power Ltd."),
        ("GEMINISEA" , "Gemini Sea Food Ltd."),
        ("GENEXIL" , "Genex Infosys Limited"),
        ("GENNEXT" , "Generation Next Fashions Limited"),
        ("GHAIL" , "Golden Harvest Agro Industries Ltd."),
        ("GHCL" , "Global Heavy Chemicals Limited"),
        ("GLOBALINS" , "Global Insurance Company Ltd."),
        ("GOLDENSON" , "Golden Son Ltd."),
        ("GP" , "Grameenphone Ltd."),
        ("GPHISPAT" , "GPH Ispat Ltd."),
        ("GQBALLPEN" , "GQ Ball Pen Industries Ltd."),
        ("GRAMEENS2" , "Grameen One : Scheme Two"),
        ("GREENDELMF" , "Green Delta Mutual Fund"),
        ("GREENDELT" , "Green Delta Insurance Ltd."),
        
        ("HAKKANIPUL" , "Hakkani Pulp & Paper Mills Ltd."),
        ("HEIDELBCEM" , "Heidelberg Cement Bangladesh Ltd."),
        ("HFL" , "Hamid Fabrics Limited"),
        ("HRTEX" , "H.R.Textile Ltd."),

        ("IBBL2PBOND" , "IBBL 2nd Perpetual Mudaraba Bond"),
        ("IBBLPBOND" , "IBBL Mudaraba Perpetual Bond"),
        ("IBNSINA" , "The IBN SINA Pharmaceutical Industry Ltd."),
        ("ICB" , "Investment Corporation Of Bangladesh"),
        ("ICB3RDNRB" , "ICB AMCL Third NRB Mutual Fund"),
        ("ICBAGRANI1" , "ICB AMCL First Agrani Bank Mutual Fund"),
        ("ICBAMCL2ND" , "ICB AMCL Second Mutual Fund"),
        ("ICBEPMF1S1" , "ICB Employees Provident MF 1: Scheme 1"),
        ("ICBIBANK" , "ICB Islamic Bank Limited"),
        ("ICBSONALI1" , "ICB AMCL Sonali Bank Limited 1st Mutual Fund"),
        ("IDLC" , "IDLC Finance Ltd."),
        ("IFADAUTOS" , "IFAD Autos Limited"),
        ("IFIC" , "IFIC Bank Ltd."),
        ("IFIC1STMF" , "IFIC Bank 1st Mutual Fund"),
        ("ILFSL" , "International Leasing & Financial Services Ltd."),
        ("IMAMBUTTON" , "Imam Button Industries Ltd."),
        ("INDEXAGRO" , "Index Agro Industries Limited"),
        ("INTECH" , "Intech Limited"),
        ("INTRACO" , "Intraco Refueling Station Limited"),
        ("IPDC" , "IPDC Finance Limited"),
        ("ISLAMIBANK" , "Islami Bank Bangladesh Limited"),
        ("ISLAMICFIN" , "Islamic Finance & Investment Ltd."),
        ("ISLAMIINS" , "Islami Insurance Bangladesh Limited"),
        ("ISNLTD" , "Information Services Network Ltd."),
        ("ITC" , "IT Consultants Limited"),
        ("JAMUNABANK" , "Jamuna Bank Ltd."),
        ("JAMUNAOIL" , "Jamuna Oil Company Limited"),
        ("JANATAINS" , "Janata Insurance Company Ltd."),
        ("JMISMDL" , "JMI Syringes & Medical Devices Ltd."),
        ("JUTESPINN" , "Jute Spinners Ltd."),
        ("KARNAPHULI" , "Karnaphuli Insurance Company Ltd."),
        ("KBPPWBIL" , "Khan Brothers PP Woven Bag Industries Limited"),
        ("KDSALTD" , "KDS Accessories Limited"),
        ("KEYACOSMET" , "Keya Cosmetics Ltd."),
        ("KOHINOOR" , "Kohinoor Chemicals Company Ltd. Bangladesh"),
        ("KPCL" , "Khulna Power Company Limited"),
        ("KPPL" , "Khulna Printing & Packaging Limited"),
        ("KTL" , "Kattali Textile Limited"),
        ("LANKABAFIN" , "LankaBangla Finance Ltd."),
        ("LEGACYFOOT" , "Legacy Footwear Ltd."),
        ("LHBL" , "LafargeHolcim Bangladesh Limited"),
        ("LIBRAINFU" , "Libra Infusions Limited"),
        ("LINDEBD" , "Linde Bangladesh Limited"),
        ("LRGLOBMF1" , "LR Global Bangladesh Mutual Fund One"),
        ("MAKSONSPIN" , "Maksons Spinning Mills Limited"),
        ("MALEKSPIN" , "Malek Spinning Mills Ltd."),
        ("MARICO" , "Marico Bangladesh Limited"),
        ("MATINSPINN" , "Matin Spinning Mills Ltd."),
        ("MBL1STMF" , "MBL 1st Mutual Fund"),
        ("MEGCONMILK" , "Meghna Condensed Milk Industries Ltd."),
        ("MEGHNACEM" , "Meghna Cement Mills Ltd."),
        ("MEGHNALIFE" , "Meghna Life Insurance Co. Ltd."),
        ("MEGHNAPET" , "Meghna Pet Industries Ltd."),
        ("MERCANBANK" , "Mercantile Bank Ltd."),
        ("MERCINS" , "Mercantile Insurance Co. Ltd."),
        ("METROSPIN" , "Metro Spinning Ltd."),
        ("MHSML" , "Mozaffar Hossain Spinning Mills Ltd."),
        ("MIDASFIN" , "MIDAS Financing Ltd."),
        ("MIRACLEIND" , "Miracle Industries Ltd."),
        ("MIRAKHTER" , "Mir Akhter Hossain Limited"),
        ("MITHUNKNIT" , "Mithun Knitting and Dyeing Ltd."),
        ("MJLBD" , "MJL Bangladesh Limited"),
        ("MLDYEING" , "M.L. Dyeing Limited"),
        ("MONNOAGML" , "Monno Agro & General Machinery Limited"),
        ("MONNOCERA" , "Monno Ceramic Industries Ltd."),
        ("MONNOFABR" , "Monno Fabrics Limited"),
        ("MONOSPOOL" , "Bangladesh Monospool Paper Manufacturing Co. Limited"),
        ("MPETROLEUM" , "Meghna Petroleum Limited"),
        ("MTB" , "Mutual Trust Bank Ltd."),
        ("NAHEEACP" , "Nahee Aluminum Composite Panel Ltd."),
        ("NATLIFEINS" , "National Life Insurance Company Ltd."),
        ("NAVANACNG" , "Navana CNG Limited"),
        ("NBL" , "National Bank Ltd."),
        ("NCCBANK" , "National Credit and Commerce Bank Ltd."),
        ("NEWLINE" , "New Line Clothings Limited"),
        ("NFML" , "National Feed Mill Limited"),
        ("NHFIL" , "National Housing Fin. and Inv. Ltd."),
        ("NITOLINS" , "Nitol Insurance Co. Ltd."),
        ("NLI1STMF" , "NLI First Mutual Fund"),
        ("NORTHERN" , "Northern Jute Manufacturing Co. Ltd."),
        ("NORTHRNINS" , "Northern Islami Insurance Limited"),
        ("NPOLYMER" , "National Polymer Industries Ltd."),
        ("NRBCBANK" , "NRB Commercial Bank Limited"),
        ("NTC" , "National Tea Company Ltd."),
        ("NTLTUBES" , "National Tubes Limited"),
        ("NURANI" , "Nurani Dyeing & Sweater Limited"),
        ("OAL" , "Olympic Accessories Limited"),
        ("OIMEX" , "Oimex Electrode Limited"),
        ("OLYMPIC" , "Olympic Industries Ltd."),
        ("ONEBANKLTD" , "One Bank Limited"),
        ("ORIONINFU" , "Orion Infusion Ltd."),
        ("ORIONPHARM" , "Orion Pharma Ltd."),
        ("PADMALIFE" , "Padma Islami Life Insurance Limited"),
        ("PADMAOIL" , "Padma Oil Co. Ltd."),
        ("PAPERPROC" , "Paper Processing & Packaging Limited"),
        ("PARAMOUNT" , "Paramount Insurance Company Ltd."),
        ("PDL" , "Pacific Denims Limited"),
        ("PENINSULA" , "The Peninsula Chittagong Limited"),
        ("PEOPLESINS" , "Peoples Insurance Company Ltd."),
        ("PF1STMF" , "Phoenix Finance 1st Mutual Fund"),
        ("PHARMAID" , "Pharma Aids"),
        ("PHENIXINS" , "Phoenix Insurance Company Ltd."),
        ("PHOENIXFIN" , "Phoenix Finance and Investments Ltd."),
        ("PHPMF1" , "PHP First Mutual Fund"),
        ("PIONEERINS" , "Pioneer Insurance Company Ltd."),
        ("PLFSL" , "Peoples Leasing and Fin. Services Ltd."),
        ("POPULAR1MF" , "Popular Life First Mutual Fund"),
        ("POPULARLIF" , "Popular Life Insurance Co. Ltd."),
        ("POWERGRID" , "Power Grid Company of Bangladesh Ltd."),
        ("PRAGATIINS" , "Pragati Insurance Ltd"),
        ("PRAGATILIF" , "Pragati Life Insurance Ltd."),
        ("PREBPBOND" , "Premier Bank Perpetual Bond"),
        ("PREMIERBAN" , "Premier Bank Ltd."),
        ("PREMIERCEM" , "Premier Cement Mills Limited"),
        ("PREMIERLEA" , "Premier Leasing & Finance Limited"),
        ("PRIME1ICBA" , "Prime Bank 1st ICB AMCL Mutual Fund"),
        ("PRIMEBANK" , "Prime Bank Ltd."),
        ("PRIMEFIN" , "Prime Finance & Investment Ltd."),
        ("PRIMEINSUR" , "Prime Insurance Company Ltd."),
        ("PRIMELIFE" , "Prime Islami Life Insurance Ltd."),
        ("PRIMETEX" , "Prime Textile Spinning Mills Limited"),
        ("PROGRESLIF" , "Progressive Life Insurance Co. Ltd."),
        ("PROVATIINS" , "Provati Insurance Company Limited"),
        ("PTL" , "Paramount Textile Limited"),
        ("PUBALIBANK" , "Pubali Bank Ltd."),
        ("PURABIGEN" , "Purabi Gen. Insurance Company Ltd."),
        ("QUASEMIND" , "Quasem Industries Ltd."),
        ("QUEENSOUTH" , "Queen South Textile Mills Limited"),
        ("RAHIMAFOOD" , "Rahima Food Corporation Limited"),
        ("RAHIMTEXT" , "Rahim Textile Mills Ltd."),
        ("RANFOUNDRY" , "Rangpur Foundry Ltd."),
        ("RDFOOD" , "Rangpur Dairy & Food Products Ltd."),
        ("REGENTTEX" , "Regent Textile Mills Limited"),
        #("RELIANCE1" , "Reliance One the first scheme of Reliance Insurance Mutual Fund"),
        ("RELIANCINS" , "Reliance Insurance Ltd."),
        ("RENATA" , "Renata Ltd."),
        ("REPUBLIC" , "Republic Insurance Company Limited"),
        ("RINGSHINE" , "Ring Shine Textiles Limited"),
        ("RNSPIN" , "R.N. Spinning Mills Limited"),
        ("ROBI" , "Robi Axiata Limited"),
        ("RUNNERAUTO" , "Runner Automobiles Limited"),
        ("RUPALIBANK" , "Rupali Bank Ltd."),
        ("RUPALIINS" , "Rupali Insurance Company Ltd."),
        ("RUPALILIFE" , "Rupali Life Insurance Company Limited"),
        ("SAFKOSPINN" , "Safko Spinnings Mills Ltd."),
        ("SAIFPOWER" , "SAIF Powertec Limited"),
        ("SAIHAMCOT" , "Saiham Cotton Mills Limited"),
        ("SAIHAMTEX" , "Saiham Textile Mills Ltd."),
        ("SALAMCRST" , "S. Alam Cold Rolled Steels Ltd."),
        ("SALVOCHEM" , "Salvo Chemical Industry Limited"),
        ("SAMATALETH" , "Samata Leather Complex Ltd."),
        ("SAMORITA" , "Samorita Hospital Limited"),
        ("SANDHANINS" , "Sandhani Life Insurance Company Ltd."),
        ("SAPORTL" , "Summit Alliance Port Limited"),
        ("SAVAREFR" , "Savar Refractories Limited"),
        ("SBACBANK" , "South Bangla Agriculture & Commerce Bank Limited"),
        ("SEAPEARL" , "Sea Pearl Beach Resort & Spa Limited"),
        ("SEMLFBSLGF" , "SEML FBLSL Growth Fund"),
        ("SEMLIBBLSF" , "SEML IBBL Shariah Fund"),
        ("SEMLLECMF" , "SEML Lecture Equity Management Fund"),
        ("SHAHJABANK" , "Shahjalal Islami Bank Ltd."),
        ("SHASHADNIM" , "Shasha Denims Limited"),
        ("SHEPHERD" , "Shepherd Industries Limited"),
        ("SHURWID" , "Shurwid Industries Limited"),
        ("SHYAMPSUG" , "Shyampur Sugar Mills Ltd."),
        ("SIBL" , "Social Islami Bank Limited"),
        ("SILCOPHL" , "Silco Pharmaceuticals Limited"),
        ("SILVAPHL" , "Silva Pharmaceuticals Limited"),
        ("SIMTEX" , "Simtex Industries Limited"),
        ("SINGERBD" , "Singer Bangladesh Limited"),
        ("SINOBANGLA" , "Sinobangla Industries Ltd."),
        ("SJIBLPBOND" , "SJIBL Mudaraba Perpetual Bond"),
        ("SKICL" , "Sena Kalyan Insurance Company Limited"),
        ("SKTRIMS" , "SK Trims & Industries Limited"),
        ("SONALIANSH" , "Sonali Aansh Industries Limited"),
        ("SONALILIFE" , "Sonali Life Insurance Company Limited"),
        ("SONALIPAPR" , "Sonali Paper & Board Mills Ltd."),
        ("SONARBAINS" , "Sonar Bangla Insurance Ltd."),
        ("SONARGAON" , "Sonargaon Textiles Ltd."),
        ("SOUTHEASTB" , "Southeast Bank Ltd."),
        ("SPCERAMICS" , "Shinepukur Ceramics Limited"),
        ("SPCL" , "Shahjibazar Power Co. Ltd."),
        ("SQUARETEXT" , "Square Textile Ltd."),
        ("SQURPHARMA" , "Square Pharmaceuticals Ltd."),
        ("SSSTEEL" , "S. S. Steel Limited"),
        ("T05Y0715" , "5 Years BGT Bonds Issued on 21.07.2010"),
        ("T05Y0815" , "5 Years BGT Bonds Issued on 18.08.2010"),
        ("T10Y0118" , "10 Years BGT Bond Issued 02.01.2008"),
        ("T10Y0119" , "10 Years BGT Bond Issued 07.01.2009"),
        ("T10Y0121" , "10 years BGT Bond Issued 05.01.2011"),
        ("T10Y0126" , "10Y BGTB 20/01/2026"),
        # ("T10Y0214" , "10 Years 8.5% BGT Bond Issued 090204"),
        # ("T10Y0215" , "10 Years 8.5% BGT Bond Issued 070205"),
        # ("T10Y0216" , "10 Years 8.5% BGT Bond Issued 13022006"),
        # ("T10Y0217" , "10 Years 8.5% BGT Bond Issued 07.02.2007"),
        ("T10Y0218" , "10 Years BGT Bond Issued 06.02.2008"),
        ("T10Y0219" , "10 Years BGT Bond Issued 04.02.2009"),
        ("T10Y0220" , "10 years BGT Bond issued on 03.02.2010"),
        ("T10Y0221" , "10 years BGT Bond Issued 02.02.2011"),
        # ("T10Y0317" , "10 Years 8.5% BGT Bond Issued 07.03.2007"),
        ("T10Y0318" , "10 Years BGT Bond Issued 05.03.2008"),
        ("T10Y0319" , "10 Years BGT Bond Issued 04.03.2009"),
        ("T10Y0320" , "10 years BGT Bond issued on 03.03.2010"),
        ("T10Y0321" , "10 years BGT Bond Issued 02.03.2011"),
        # ("T10Y0414" , "10 Years 8.5% BGT Bond Issued 050404"),
        # ("T10Y0415" , "10 Years 8.5% BGT Bond Issued 040405"),
        # ("T10Y0416" , "10 Years 8.5% BGT Bond Issued 10042006"),
        ("T10Y0418" , "10 Years BGT Bond Issued 02.04.2008"),
        ("T10Y0419" , "10 Years BGT Bond Issued 08.04.2009"),
        ("T10Y0420" , "10 years BGT Bond Issued on 07.04.2010"),
        ("T10Y0421" , "10 years BGT Bond Issued 06.04.2011"),
        ("T10Y0517" , "10 Years BGT Bond Issued 09.05.2007"),
        ("T10Y0518" , "10 Years BGT Bond Issued 07.05.2008"),
        ("T10Y0519" , "10 Years BGT Bond Issued 06.05.2009"),
        ("T10Y0520" , "10 years BGT Bond Issued 05.05.2010"),
        ("T10Y0521" , "10 years BGT Bond Issued 04.05.2011"),
        # ("T10Y0614" , "10 Years 8.5% BGT Bond Issued 070604"),
        # ("T10Y0615" , "10 Years 8.5% BGT Bond Issued 060605"),
        # ("T10Y0616" , "10 Years 8.5% BGT Bond Issued 12062006"),
        ("T10Y0617" , "10 Years BGT Bond Issued 06.06.2007"),
        ("T10Y0618" , "10 Years BGT Bond Issued 04.06.2008"),
        ("T10Y0619" , "10 Years BGT Bond Issued 03.06.2009"),
        ("T10Y0620" , "10 Years BGT Bond Issued 02.06.2010"),
        ("T10Y0621" , "10 years BGT Bond Issued 08.06.2011"),
        ("T10Y0717" , "10 Years BGT Bond Issued 04.07.2007"),
        ("UCB" , "United Commercial Bank Ltd."),
        ("UNILEVERCL" , "Unilever Consumer Care Limited"),
        ("UNIONBANK" , "Union Bank Limited"),
        ("UNIONCAP" , "Union Capital Limited"),
        ("UNIONINS" , "Union Insurance Company Limited"),
        ("UNIQUEHRL" , "Unique Hotel & Resorts Limited"),
        ("UNITEDFIN" , "United Finance Limited"),
        ("UNITEDINS" , "United Insurance Ltd."),
        ("UPGDCL" , "United Power Generation & Distribution Company Ltd."),
        ("USMANIAGL" , "Usmania Glass Sheet Factory Limited"),
        ("UTTARABANK" , "Uttara Bank Limited"),
        ("UTTARAFIN" , "Uttara Finance and Investments Limited"),
        ("VAMLBDMF1" , "Vanguard AML BD Finance Mutual Fund One"),
        ("VAMLRBBF" , "Vanguard AML Rupali Bank Balanced Fund"),
        ("VFSTDL" , "VFS Thread Dyeing Limited"),
        ("WALTONHIL" , "Walton Tech Industries PLC"),
        ("WATACHEM" , "Wata Chemicals Limited"),
        ("WMSHIPYARD" , "Western Marine Shipyard Limited"),
        ("YPL" , "Yeakin Polymer Limited"),
        ("ZAHEENSPIN" , "Zaheen Spinning Limited"),
        ("ZAHINTEX" , "Zahintex Industries Limited"),
        ("ZEALBANGLA" , "Zeal Bangla Sugar Mills Ltd."),
        ("1JANATAMF" , "First Janata Bank Mutual Fund"),
        ("1STPRIMFMF" , "Prime Finance First Mutual Fund"), 
    ]
    trading_code = models.CharField(max_length=200, choices=select_tradingCode, default="None")
    
    def __str__(self):
        return self.trading_code
    
    

class Contact(models.Model):
    full_name=models.CharField(max_length=100)
    email=models.CharField(max_length=200)
    message=models.TextField()

    def __str__(self):
        return self.full_name
