# Generated by Django 4.0.1 on 2022-04-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(blank=True, max_length=255, null=True)),
                ('news', models.CharField(blank=True, max_length=10000, null=True)),
                ('news_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_trading_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_info', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
    ]
