# Generated by Django 4.0.1 on 2022-01-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinput',
            name='username',
            field=models.CharField(default='NULL User', max_length=50),
        ),
    ]
