# Generated by Django 4.0.1 on 2022-01-29 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
