# Generated by Django 4.0.1 on 2022-03-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_delete_usermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='trading_code',
            field=models.CharField(choices=[('ACFL', 'Aman Cotton Fibrous Limited'), ('EXCH', 'EXCH')], default='Select', max_length=200),
        ),
    ]
